---
name: upload de github pages
  # Le workflow se déclenchera quand on fera un git push sur main
on:
  push:
    branches:
    - main
jobs:
  # Build job
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - name: Get index.html from repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            index.html
          sparse-checkout-cone-mode: false     
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: .
          
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4