---
    name: preprod release
    
    on:
      workflow_dispatch:
      push:
        branches:
          - pre_prod
    
    jobs:
      build:
        runs-on: ubuntu-latest
    
        steps:
          - name: Get data from repository
            uses: actions/checkout@v4
    
             
          - name: Upload static files as artifact
            id: deployment
            uses: actions/upload-artifact@v4 # or specific "vX.X.X" version tag for this action
            with:
              path: site/
              name: mapage
      deploy:
        runs-on: 
          - self-hosted
        needs: build
        steps:
          - uses: actions/download-artifact@v4
            with:
              path: /var/www/html
              name: mapage