---
name: preprod release
  
on:
  workflow_dispatch:
  push:
    branches:
      - pre_prod
  
jobs:
     
  # Build job (https://github.com/actions/upload-pages-artifact?tab=readme-ov-file)
  build:
    # Specify runner +  build & upload the static files as an artifact (https://github.com/marketplace/actions/upload-a-build-artifact)
    runs-on: ubuntu-latest
    steps:
      - name: Get index.html from repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            index.html
          sparse-checkout-cone-mode: false

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-artifact@v4 # or specific "vX.X.X" version tag for this action
        with:
          path: .

  
  deploy:
    
      runs-on: 
        - self-hosted
      needs: build
      steps:
        - uses: actions/download-artifact@v4
          with:
            path: /var/www/html
            # name: mapage